### ISSUE TITLE
Can't install IKTrading

### ISSUE THREAD

**Issue by mattpa** [IlyaKipnis/IKTrading#8]
I am on Windows 10. Following the R bloggers code recently published on Quantstrat.

install_github("IKTrading", username = "IlyaKipnis")

When I run this code I get this:

install_github("IKTrading", username = "IlyaKipnis")
Downloading GitHub repo IlyaKipnis/IKTrading@master
from URL https://api.github.com/repos/IlyaKipnis/IKTrading/zipball/master
Installing IKTrading
Installing 1 package: digest
Installing package into ‘C:/Users/Matt/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/digest_0.6.12.zip'
Content type 'application/zip' length 172732 bytes (168 KB)
downloaded 168 KB

package ‘digest’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘digest’

The downloaded binary packages are in
	C:\Users\Matt\AppData\Local\Temp\RtmpOaRqoz\downloaded_packages
Installing 1 package: quantmod
Installing package into ‘C:/Users/Matt/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning: package ‘quantmod’ is in use and will not be installed
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Matt/AppData/Local/Temp/RtmpOaRqoz/devtools2b946dd67cef/IlyaKipnis-IKTrading-0b4e0e5"  \
  --library="C:/Users/Matt/Documents/R/win-library/3.3" --install-tests 

ERROR: dependency 'digest' is not available for package 'IKTrading'
* removing 'C:/Users/Matt/Documents/R/win-library/3.3/IKTrading'
Error: Command failed (1)
In addition: Warning message:
Username parameter is deprecated. Please use IlyaKipnis/IKTrading 

When I try the username "IllyKipnis/IKTrading" I get this error:

nstall_github("IKTrading", username = "IlyaKipnis/IKTrading")
Downloading GitHub repo IlyaKipnis/IKTrading/IKTrading@master
from URL https://api.github.com/repos/IlyaKipnis/IKTrading/IKTrading/zipball/master
Error in stop(github_error(request)) : Not Found (404)
In addition: Warning message:
Username parameter is deprecated. Please use IlyaKipnis/IKTrading/IKTrading 

Any ideas how to proceed?

**Comment by IlyaKipnis** [comment]
Install roxygen2 from CRAN, then
try install_github(repo="IlyaKipnis/IKTrading")

**Comment by mattpa** [comment]
It worked! Thank you. I just took your course on DataCamp. Not sure if you presenting others or on other platforms, but would be interested to know if you are. Thanks again for the quick response.

**Comment by mandarpriya** [comment]
Todaz i went through the similar issues, and found that when installing, it asks for re-installation of some libraries like TTR, Curl etc. , surprisingly again installs quantstrat. Finally the package was installed
